askbuddie/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views
from django.conf import settings
app_name = "app_askbuddie"
urlpatterns = [
    path("thread/<slug:slug>/",views.DetailThread.as_view(),name="askbuddie_thread"),
    path("search/",views.SearchForumView.as_view(),name="askbuddie_search"),
    path("create-topic/",views.CreateTopic.as_view(),name="askbuddie_create"),
    path("mostliked/",views.MostLikedView.as_view(),name="askbuddie_mostliked"),
    path("unread/",views.UnreadView.as_view(),name="askbuddie_unread"),
    path("signup/",views.SignupView.as_view(),name="askbuddie_signup"),
    path("login/",views.MyLoginView.as_view(),name="askbuddie_login"),
    path("logout/",views.MyLogoutView.as_view(),name="askbuddie_logout"),
    path("support/",views.SupportView.as_view(),name="askbuddie_support"),
    path("forgot-password/",views.ForgotPassword.as_view(),name="askbuddie_forgot"),
    path("tag/<str:tag>/",views.TagForumView.as_view(),name="askbuddie_tag"),
    path("category/<str:category>/",views.CategoryForumView.as_view(),name="askbuddie_category"),
    path("<slug:slug>/",views.SinglePage.as_view(),name="askbuddie_page"),
    path("",views.IndexThread.as_view(),name="askbuddie_home"),
]

forum/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps import views
from django.contrib.sitemaps.views import sitemap
from askbuddie.sitemap import ForumThreadSitemap,PageSitemap,StaticSitemap
from askbuddie.models import BaseConfig
# admin.site.site_header = BaseConfig.objects.first().header
# admin.site.index_title = f"{admin.site.site_header} Admin Dashboard"
# admin.site.site_title = f"{admin.site.site_header} Admin"
# admin.AdminSite.login_template = 'askbuddie/login.html'
sitemaps = {
    "threads":ForumThreadSitemap,
    "pages":PageSitemap,
    "static":StaticSitemap,
}
urlpatterns = [
    path('logmein/', admin.site.urls),
    path("",include("askbuddie.urls",namespace="askbuddie")),
    path('editor/', include('django_summernote.urls')),
    path("map.xml",views.index,{"sitemaps":sitemaps},name="django.contrib.sitemaps.views.sitemap"),
    path('map-<section>.xml', views.sitemap, {'sitemaps': sitemaps},name='django.contrib.sitemaps.views.sitemap'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
else:
    handler404 = "forum.handlers.page_not_found"
    handler500 = "forum.handlers.server_error"

askbuddie/models/configModel.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.urls import reverse
class BaseConfig(models.Model):
    title = models.CharField(max_length=30,help_text="Only One Instance Is Allowed")
    logo = models.ImageField(upload_to="logo",null=True,blank=True)
    favicon = models.ImageField(upload_to="favicon",null=True,blank=True)
    header = models.CharField(max_length=15)
    author = models.OneToOneField(User,on_delete=models.CASCADE,related_name="base_author",default=1)
    analytics = models.CharField(max_length=20,null=True,blank=True)
    description = models.TextField(null=True,blank=True)
    def save(self,*args,**kwargs):
        self.id=1
        return super().save(*args,**kwargs)
    def __str__(self) -> str:
        return self.title
    
    class Meta:
        verbose_name_plural = "BaseConfig"
class SocialMedia(models.Model):
    baseConfig = models.ForeignKey(BaseConfig,on_delete=models.CASCADE,related_name="base_social")
    platform = models.CharField(max_length=12,help_text="Example: Facebook,Instagram",unique=True)
    url = models.URLField(max_length=283,help_text="Example: https://www.facebook.com/Shuvraj.lama7")
    css_class = models.CharField(max_length=30,null=True,blank=True,help_text="FontAwesome. Example: facebook-square")
    def __str__(self)-> str:
        return self.platform
    class Meta:
        verbose_name_plural = "SocialMedias"
class BasePage(models.Model):
    baseConfig = models.ForeignKey(BaseConfig,on_delete=models.CASCADE,related_name="base_page")
    title = models.CharField(max_length=20,unique=True)
    description = models.TextField(blank=True,null=True)
    slug = models.SlugField(null=True,blank=True)
    class Meta:
        verbose_name_plural = "BasePages"
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse("app_askbuddie:askbuddie_page", kwargs={"slug": self.slug})
    def save(self,*args,**kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args,**kwargs)
class BaseTag(models.Model):
    baseConfig = models.ForeignKey(BaseConfig,on_delete=models.CASCADE,related_name="base_tag")
    name = models.CharField(max_length=20)
    class Meta:
        verbose_name_plural = "BaseTags"
    def __str__(self):
        return self.name

askbuddie/models/userModel.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.contrib.auth.backends import ModelBackend
from django.db.models import Q
from django.contrib.auth.models import User
User._meta.get_field('email')._unique = True

class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,related_name="user_profile")
    profile = models.ImageField(upload_to="profile",null=True,default="profile/default.png")
    send_newsletter = models.BooleanField(default=False)
    socialHandle = models.URLField(max_length=283,null=True,blank=True)
class EmailBackend(ModelBackend):
    def authenticate(self, request, username=None, password=None, **kwargs):
        UserModel = get_user_model()
        try:
            user = UserModel.objects.get(Q(username=username)|Q(email=username))
        except UserModel.DoesNotExist:
            return None
        else:
            if user.check_password(password):
                return user
        return None

askbuddie/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User
from askbuddie.models import ForumThread,ThreadReply,Support
from django.contrib.auth.forms import UserCreationForm
from django_summernote.widgets import SummernoteWidget
import asyncio
import aiohttp
from django.conf import settings
async def verifyRecaptcha(token):
    payload = {"secret":settings.RECAPTCHA_SECRET_KEY,"response":token}
    async with aiohttp.ClientSession() as session:
        async with session.post("https://www.google.com/recaptcha/api/siteverify",data=payload) as response:
            output = await response.json()
            return output.get("success")
class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(widget=forms.TextInput(attrs={"required":True,}))
    terms = forms.BooleanField(required=False)
    class Meta:
        model = User
        fields = ["first_name","last_name","username","email",
        "password1","password2","terms",]
    def clean_terms(self):
        value = self.cleaned_data.get("terms")
        if not value:
            self.add_error("terms","Agree to terms & conditions to Sign Up.")
        return value
class ForumThreadForm(forms.ModelForm):
    tags = forms.CharField(widget=forms.TextInput(attrs={"required":False,}))
    class Meta:
        model = ForumThread
        exclude = ("created_by","slug","closed",'views',)
        widgets = {
            "description":SummernoteWidget(),
        }
class ThreadReplyForm(forms.ModelForm):
    class Meta:
        model = ThreadReply
        fields = ("description",)
        widgets = {
            "description":SummernoteWidget(),
        }
class SupportForm(forms.ModelForm):
    class Meta:
        model = Support
        exclude = ("user",)

askbuddie/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate
from django.conf import settings
from django.contrib.messages.views import SuccessMessageMixin
from .forms import (
    UserRegistrationForm,
    verifyRecaptcha,
    ForumThreadForm,
    ThreadReplyForm,
    SupportForm,
)
from django.contrib.auth.views import (
    LoginView,
    LogoutView
)
from django.views.generic import (
    ListView,
    DetailView,
    View,
    CreateView,
    FormView
)
from askbuddie.models import (
    ForumThread,
    BasePage,
    ThreadTag,
)
from django.db.models import (
    Sum,
    Count
)
from django.urls import (
    reverse_lazy,
    reverse
)
from django.contrib.auth.mixins import (
    UserPassesTestMixin,
    LoginRequiredMixin,
)

from django.http import (
    HttpResponseNotModified,
    HttpResponseRedirect,
)
import asyncio,random
from urllib.parse import unquote_plus
from django.http import HttpResponse
class IndexThread(ListView):
    model = ForumThread
    template_name = "askbuddie/home.html"
    context_object_name = "threads"
    paginate_by = 20
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["status"] = "Latest"
        return context
    def get_queryset(self):
        return self.model.objects.all().select_related("created_by")
    
class DetailThread(DetailView):
    model = ForumThread
    template_name = "askbuddie/detail.html"
    context_object_name = "thread"
    def post(self,request,*args,**kwargs):
        reply = ThreadReplyForm(request.POST,request.FILES) 
        if reply.is_valid():
            reply = reply.save(commit=False)
            reply.created_by = request.user
            reply.forumThread = self.get_object()
            reply.save()
        return super().get(request,*args,**kwargs)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.object.views +=1
        self.object.save(update_fields=["views",])
        context["form"] = ThreadReplyForm()
        context["thread_likes"]=self.object.thread_reply.aggregate(upvotes=Sum("upvotes")).get("upvotes")
        context["thread_users"] = self.object.thread_reply.aggregate(users=Count("created_by")).get("users")
        return context
class SearchForumView(ListView):
    model = ForumThread
    template_name = "askbuddie/home.html"
    context_object_name = "threads"
    paginate_by = 20
    def get(self,request,*args,**kwargs):
        if not request.GET.get("thread"):
            return HttpResponseNotModified()
        return super().get(request,*args,**kwargs)
    def get_queryset(self):
        query = self.request.GET.get("thread")
        threads = ForumThread.objects.filter(topic__icontains=query)|ForumThread.objects.filter(withTag__tag__icontains=query)
        return threads
class CategoryForumView(ListView):
    model = ForumThread
    template_name = "askbuddie/home.html"
    context_object_name = "threads"
    paginate_by = 20
    def get_queryset(self):
        threads = self.model.objects.filter(category__icontains=self.kwargs.get("category"))
        return threads
class TagForumView(CategoryForumView):
    def get_queryset(self):
        threads = self.model.objects.filter(withTag__tag__icontains=unquote_plus(self.kwargs.get("tag")))
        return threads
class MostLikedView(CategoryForumView):
    def get_queryset(self):
        threads = self.model.objects.annotate(upvotes=Sum("withThreadReply__upvotes")).order_by("-upvotes")
        return threads
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context["status"] = "Most Liked"
        return context
class UnreadView(CategoryForumView):
    def get_queryset(self):
        threads = self.model.objects.filter(views=0)
        return threads
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context["status"] = "Unread"
        return context
class MyLoginView(UserPassesTestMixin,SuccessMessageMixin,LoginView):
    template_name = "askbuddie/login.html"
    success_login_messages=["Welcome back! %s .This place hasn't been the same without you",
    "So Glad You're Back,%s","Welcome back! %s .There will be forcefull resistance if you ever try to leave again",]
    def get_success_url(self):
        return reverse("app_askbuddie:askbuddie_home")
    def get_success_message(self,cleaned_data):
        self.success_message = random.choice(self.success_login_messages)% self.request.user.first_name
        return super().get_success_message(cleaned_data)
    def form_valid(self,form):
        recaptcha_token = self.request.POST.get("g-recaptcha-response")
        if asyncio.run(verifyRecaptcha(recaptcha_token)):
            return super().form_valid(form)
        form.add_error(None,"Human Verification Failed.Try Again")
        return super().form_invalid(form)
    def test_func(self):
        return self.request.user.is_anonymous
    def handle_no_permission(self):
        return HttpResponseRedirect(reverse("app_askbuddie:askbuddie_home"))
class MyLogoutView(LoginRequiredMixin,LogoutView):
    pass
class SinglePage(DetailView):
    model = BasePage
    template_name = "askbuddie/singlepage.html"
    context_object_name = "page"

class ForgotPassword(View):
    template_name = "askbuddie/forgot.html"
    def get(self,request):
        return render(request,self.template_name)
class SignupView(UserPassesTestMixin,SuccessMessageMixin,CreateView):
    form_class = UserRegistrationForm
    template_name = "askbuddie/signup.html"
    success_message = "Welcome Nerds"
    def get_success_url(self):
        return reverse("app_askbuddie:askbuddie_login")
    def get_success_message(self,cleaned_data):
        self.success_message = "You're Welcome! Nerd"
        return super().get_success_message(cleaned_data)
    def form_valid(self,form):
        recaptcha_token = self.request.POST.get("g-recaptcha-response")
        if asyncio.run(verifyRecaptcha(recaptcha_token)):
            form_response = super().form_valid(form)
            user = authenticate(username = form.cleaned_data.get("username"),password=form.cleaned_data.get("password1"))
            if self.request.POST.get("send_newsletter"):
                user.user_profile.send_newsletter=True
                user.user_profile.save()
            login(self.request,user)
            return form_response
        form.add_error(None,"Human Verification Failed.Try Again")
        return super().form_invalid(form)
    def test_func(self):
        return self.request.user.is_anonymous
    def handle_no_permission(self):
        return redirect("app_askbuddie:askbuddie_home")
class CreateTopic(LoginRequiredMixin,CreateView):
    form_class = ForumThreadForm
    template_name = "askbuddie/create-topic.html"
    def form_valid(self,form):
        form.instance.created_by = self.request.user
        formResponse = super().form_valid(form)
        tags = form.cleaned_data.get("tags","").split(",")
        # tags.remove("")
        #use if tag to check if the tag is empty string or not
        for tag in tags:
            if tag and form.instance.forum_tag.count()<7:
                threadtag,created=ThreadTag.objects.get_or_create(tag=tag)
                threadtag.forumThread.add(form.instance)
        if not settings.DEBUG:
            fb_post_id = settings.FB.post(form.instance.topic,link=f"{self.request.get_host()}{form.instance.get_absolute_url()}")
            form.instance.fb_post_id = fb_post_id
            form.instance.save()
        return formResponse
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["threads"] = random.choices(ForumThread.objects.all(),k=10)
        return context
    
class SupportView(SuccessMessageMixin,CreateView):
    form_class = SupportForm
    template_name = "askbuddie/support.html"
    success_message = "Submitted Successfully"
    def form_valid(self,form):
        recaptcha_token = self.request.POST.get("g-recaptcha-response")
        if asyncio.run(verifyRecaptcha(recaptcha_token)):
            if self.request.user.is_authenticated:
                form.instance.user = self.request.user
                form.instance.email = self.request.user.email
            else:
                if not form.cleaned_data.get("email"):
                    form.add_error("email","Please provide an email")
                    return super().form_invalid(form)
            return super().form_valid(form)
        form.add_error(None,"Human Verification Failed.Try Again")
        return super().form_invalid(form)

askbuddie/templates/askbuddie/create-topic.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Create Thread - {{config.title}} {% endblock title %}
{% block author %} {{request.get_host}} {% endblock author %}
{% block content %}
<div class="create">
    <div class="create__head">
        <div class="create__title"><img src="{% static 'askbuddie/fonts/icons/main/New_Topic.svg' %}" alt="New topic">Create New Thread</div>
        <span><a href="{% url 'app_askbuddie:askbuddie_page' 'form-guidelines' %}">Forum Guidelines</a></span>
    </div>
    <form method="post">
        {% csrf_token %}
        {% for error in form.topic.errors %}
            <div class="alert alert-danger">{{error}}</div>
        {% endfor %}
        <div class="create__section">
            <label class="create__label" for="title">Thread Title</label>
            <input type="text" class="form-control" id="title" name="topic" placeholder="Add here">
        </div>
          {% for error in form.category.errors %}
            <div class="alert alert-danger">{{error}}</div>
        {% endfor %}
        <div class="row">
            <div class="col-md-6">
                <div class="create__section">
                    <label class="create__label" for="category">Select Category</label>
                    <label class="custom-select">
                        <select id="category" name="category">
                            <option>Choose</option>
                            {% for category in category_choices %}
                            <option value="{{category.1|lower}}">{{category.1}}</option>
                            {% endfor %}
                        </select>
                    </label>
                </div>
            </div>
            {% comment %} <div class="col-md-6"> 
                <div class="create__section">
                    <label class="create__label" for="sub-category">Select Sub Category</label>
                    <label class="custom-select">
                        <select id="sub-category">
                            <option>Choose</option>
                            <option>Choose #2</option>
                            <option>Choose #3</option>
                        </select>
                    </label>
                </div>
            </div> {% endcomment %}
        </div>
          {% for error in form.description.errors %}
            <div class="alert alert-danger">{{error}}</div>
        {% endfor %}
        <div class="create__section create__textarea">
            <label class="create__label" for="description">Description</label>
            {{form.description}}
        </div>
          {% for error in form.tags.errors %}
            <div class="alert alert-danger">{{error}}</div>
        {% endfor %}
        <div class="create__section">
            <label class="create__label" for="tags">Add Tags</label>
            <input type="text" class="form-control" id="tags" name="tags" placeholder="e.g. nature, science">
        </div>
        {% comment %} <div class="create__advanced">
            <div class="row">
                <div class="col-lg-4 col-xl-4">
                    <div class="create__section">
                        <label class="create__label">Who can see this?</label>
                        <div class="create__radio">
                            <label class="create__box">
                                <label class="custom-radio">
                                    <input type="radio" name="can-see" checked="checked">
                                    <i></i>
                                </label>
                                <span>Everyone</span>
                            </label>
                            <label class="create__box">
                                <label class="custom-radio">
                                    <input type="radio" name="can-see">
                                    <i></i>
                                </label>
                                <span>Only Friends</span>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-xl-3">
                    <div class="create__section">
                        <label class="create__label">Share on Social?</label>
                        <div class="create__radio">
                            <label class="create__box">
                                <label class="custom-checkbox">
                                    <input type="checkbox" name="share-social" checked="checked">
                                    <i></i>
                                </label>
                                <i class="fa fa-facebook-square" aria-hidden="true"></i>
                            </label>
                            <label class="create__box">
                                <label class="custom-checkbox">
                                    <input type="checkbox" name="share-social" checked="checked">
                                    <i></i>
                                </label>
                                <i class="fa fa-twitter" aria-hidden="true"></i>
                            </label>
                            <label class="create__box">
                                <label class="custom-checkbox">
                                    <input type="checkbox" name="share-social">
                                    <i></i>
                                </label>
                                <i class="fa fa-google-plus" aria-hidden="true"></i>
                            </label>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-xl-5">
                    <div class="create__section">
                        <label class="create__label">Is this a Mature Thread?</label>
                        <div class="create__radio">
                            <label class="create__box">
                                <label class="custom-radio">
                                    <input type="radio" name="mature-thread">
                                    <i></i>
                                </label>
                                <span>Yes</span>
                            </label>
                            <label class="create__box">
                                <label class="custom-radio">
                                    <input type="radio" name="mature-thread" checked="checked">
                                    <i></i>
                                </label>
                                <span>No</span>
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div> {% endcomment %}
        <div class="create__footer">
            <a href='' class="create__btn-cansel btn">Cancel</a>
            <button type="submit" class="create__btn-create btn btn--type-02">Create Thread</button>
        </div>
    </form>
</div>
<div class="posts" data-visible="desktop">
    <div class="posts__head">
        <div class="posts__topic">Topic</div>
        <div class="posts__category">Category</div>
        <div class="posts__users">Users</div>
        <div class="posts__replies">Replies</div>
        <div class="posts__views">Views</div>
        <div class="posts__activity">Activity</div>
    </div>
    <div class="posts__body">
        {% for thread in threads %}
        <div class="posts__item {% cycle 'bg-f2f4f6' '' 'posts__item--bg-gradient' %}">
            <div class="posts__section-left">
                <div class="posts__topic">
                    <div class="posts__content">
                        <a href="{% url 'askbuddie:askbuddie_thread' thread.slug %}">
                            <h3>{{thread.topic}}</h3>
                        </a>
                        <div class="posts__tags tags">
                            {% for tag in thread.forum_tag.all %}
                            <a href="{% url 'askbuddie:askbuddie_tag' tag %}" class="{{tag|random_color_generator}}">{{tag}}</a> {% endfor %}
                        </div>
                    </div>
                </div>
                {%with category=thread.get_category_display|split:"," %}
                <div class="posts__category"><a href="{% url 'askbuddie:askbuddie_category' category.0 %}" class="category"><i class="{{category.0|color}}"></i> {{category.0}}</a></div>
                {% endwith %}
            </div>
            <div class="posts__section-right">
                <div class="posts__users js-dropdown">
                    {% for reply in thread.thread_reply.all|slice:"4" %} {% with user=reply.created_by %}{% ifchanged user %}
                    <div>
                        <a href="#" class="avatar"><img src="{{user.user_profile.profile.url}}" alt="{{user.first_name}}" data-dropdown-btn="{{user.id}}"></a>
                        <div class="posts__users-dropdown dropdown dropdown--user dropdown--reverse-y" data-dropdown-list="{{user.id}}">
                            <div class="dropdown__user">
                                <a href="#" class="dropdown__user-label"><img src="{{user.user_profile.profile.url}}" alt="{{user.first_name}}"></a>
                                <div class="dropdown__user-nav">
                                    <a href="#"><i class="icon-Add_User"></i></a>
                                    <a href="#"><i class="icon-Message"></i></a>
                                </div>
                                <div class="dropdown__user-info">
                                    <a href="#">{{user.get_full_name}}</a>
                                    <p>Last Online: {{user.last_login|user_last_online_timesince}}.<br/> Joined: {{user.date_joined|date:"d M,Y"}}.</p>
                                </div>
                                <div class="dropdown__user-icons">
                                    <a href="#"><img src="{% static 'askbuddie/fonts/icons/badges/Intermediate.svg' %}" alt="user-icon"></a>
                                    <a href="#"><img src="{% static 'askbuddie/fonts/icons/badges/Bot.svg' %}" alt="user-icon"></a>
                                    <a href="#"><img src="{% static 'askbuddie/fonts/icons/badges/Animal_Lover.svg' %}" alt="user-icon"></a>
                                </div>
                                <div class="dropdown__user-statistic">
                                    <div>Threads - <span>{{user.user_thread.count}}</span></div>
                                    <div>Posts - <span>{{user.user_reply.count}}</span></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endifchanged %} {% endwith %} {% endfor %}
                    <!--
                        add more user here
                    -->
                </div>
                <div class="posts__replies">{{thread.thread_reply.count}}</div>
                <div class="posts__views">{% if thread.views >= 1000 %}{{thread.views|div:"1000"}}K{% else %} {{thread.views}}{% endif %}</div>
                <div class="posts__activity">{{thread|activity}}</div>
            </div>
        </div>
        {% empty %}
        {% block extra_head %}
        <style>
            .card:hover{
            transform: scale(1.05);
        box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 4px 8px rgba(0,0,0,.06);  cursor: pointer;}
        </style>
        {% endblock extra_head %}
        <div class="card m-4 text-center mx-auto">
            <div class="card-header text-dark">
                No Thread Found
            </div>
        </div>
        {% endfor %}
        
    </div>
</div>

{% endblock content %}

askbuddie/templates/askbuddie/loginV1.html
{% extends 'askbuddie/credentialBase.html' %} {% block title %}Login{% endblock title %} {% block content %} {% for error in form.non_field_errors %}
<div class="alert alert-danger">{{error}}</div>
{% endfor %}
<div class="form__field form__field--email">
    <label class="label label--icon" for="login__email">
      <svg class="icon">
        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#user"></use>
      </svg>
      <span class="hidden">Email</span>
    </label>
    <div class="form__input-wrapper">
        <input id="login__email" type="text" autocomplete="off" name="username" class="form__input" placeholder="Email or Username" required>
        <!--
              FF is ignoring position relative of form__input-wrapper so added a wrapper for .underline.
              NOTE: just the precense of this comment fixes this FF issue (making the underline-wrapper unncessary).
              But I'd rather not rely on a comment.
            -->
        <div class="underline-wrapper">
            <span class="underline"></span>
        </div>
    </div>
</div>

<div class="form__field form__field--password">
    <label class="label label--icon" for="login__password">
      <svg class="icon">
        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#lock"></use>
      </svg>
      <span class="hidden">Password</span>
    </label>
    <div class="form__input-wrapper">
        <input id="login__password" type="password" name="password" class="form__input" placeholder="Password" required>
        <!--
              FF is ignoring position relative of form__input-wrapper so added a wrapper for .underline.
              NOTE: just the precense of this comment fixes this FF issue (making the underline-wrapper unncessary).
              But I'd rather not rely on a comment.
            -->
        <div class="underline-wrapper">
            <span class="underline"></span>
        </div>
    </div>
</div>

<div class="login-actions-container">
    <div class="form__field form__field--submit">
        {% include 'askbuddie/captcha.html' %}
    </div>
    <div class="form__field form__field--remember-me">
        <label class="label label--remember-me" for="login__remember-me">
        <input id="login__remember-me" type="checkbox">
        <span class="checkmark"></span>
        <span class="remember-me-text">Remember me</span>
      </label>
    </div>
    <a class="forgot-password" href="{% url 'app_askbuddie:askbuddie_forgot' %}">Forgot Password?</a>
    <a class="forgot-password" href="{% url 'app_askbuddie:askbuddie_signup' %}">Don't have an account?</a>

    <div class="form__field form__field--submit">
        <input type="submit" value="log in">
    </div>
</div>
{% endblock content %}